### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by baali** [mayankkhatri7/project-url#1]
A basic documentation around the project, introduction. This might be helpful: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes

**Comment by mayankkhatri7** [comment]
Done with the format fixing and rewording.
Please check and update.

**Comment by baali** [comment]
The PR could have been directly merged into the Repo and you wouldn't have to redo everything I had done in the README file.
