### ISSUE TITLE
Remove pyc files

### ISSUE THREAD

**Issue by baali** [mayankkhatri7/project-url#3]
You have added pyc file to he repo, in general it is [advised](https://github.com/mayankkhatri7/project-url/tree/master/mysite/__pycache__) to avoid them. 

Checkout [`.gitignore`](https://git-scm.com/docs/gitignore) and see if you can disable them for being tracked by `git`.

**Comment by mayankkhatri7** [comment]
okay, i'll try to find a alternate of this.
and will go through the advised link as well.

**Comment by baali** [comment]
I did a quick google search using terms: `git rm pyc files` and got a link on how to do this: https://stackoverflow.com/a/26097537 
Do explore .gitignore file and add it to the repo.

**Comment by mayankkhatri7** [comment]
I had removed/ignored pyc files but unable to add it back to repo.

**Comment by baali** [comment]
It seems you have `renamed` pyc files in e073f462a. I would suggest read up more on Git. A friend of mine has put together some good resources around `git`: https://punchagan.muse-amuse.in/blog/git-resources/. He mentions about this git resource being really good: https://zulip.readthedocs.io/en/latest/git/index.html
